import {
    Box,
    Grid,
    Table,
    TableBody,
    TableCell,
    TableContainer,
    TableHead,
    TableRow,
} from "@mui/material";
import { BarChart, XAxis, YAxis, Tooltip, Bar, Rectangle, ResponsiveContainer } from "recharts";
import HeaderFooter from "../HeaderFooter";
import { useEffect, useMemo, useState } from "react";
import { colors } from "../../theme";
import { isEmpty, range } from "lodash";
import binomcoef from "@stdlib/math-base-special-binomcoef";

export type BarDatum = { name: string; proportion: number };

const sum = (acc: number, i: number) => acc + i;

function rollsUntilDepleted(p: number, n: number): number {
    const trials = Math.pow(10, 4);
    if (n == 0) {
        return 1;
    } else {
        return range(0, trials)
            .map((roll) => roll * probabilityNumberOfRollsToDeplete(p, n, roll))
            .reduce(sum);
    }
}

function probabilityNumberOfRollsToDeplete(p: number, n: number, r: number): number {
    const q = 1 - p;
    return Math.pow(1 - Math.pow(q, r), n) - Math.pow(1 - Math.pow(q, r - 1), n);
}

export function proportionFormat(value: number) {
    const proportion = value > 1e-3 ? value.toFixed(3) : value === 0 ? 0 : value.toExponential(3);
    const percent = value * 100;
    const percentDisplay = percent < 1 ? percent.toPrecision(2) : percent.toPrecision(3);
    return `${proportion} (${percentDisplay}%)`;
}

const info = (
    <>
        The data on this page was generated by simulating 10^8 trials of rolling a pool of dice
        until it was depleted. Fun fact - the number of rolls until a diminishing pool of n dice is
        depleted can be expressed as the maximum of n i.i.d. geometric random variables with p=0.5.
        However, the expected value of that distribution is not straightforward to calculate at all
        for n&gt;1.{" "}
        <a href="https://www.sciencedirect.com/science/article/abs/pii/S0167715207002040">
            Here's a paper about it!
        </a>
    </>
);
export default function DiminishingPoolAnalysis() {
    const [p, setP] = useState(0.5);
    const [selectedNumDice, setSelectedNumDice] = useState(4);
    const [selectedResults, setSelectedResults] = useState<BarDatum[]>([]);
    const trials = 100;
    const expectedValues = useMemo(
        () => range(1, 100 + 1).map((n) => [n, rollsUntilDepleted(p, n)]),
        []
    );

    useEffect(() => {
        const epsilon = 1e-6;
        const probabilities: [number, number][] = [];
        let roll = 1;
        let avg = 0;
        const expectedValue = expectedValues[selectedNumDice - 1][1];
        while (probabilities.length < trials && Math.abs(avg - expectedValue) > epsilon) {
            const probability = probabilityNumberOfRollsToDeplete(p, selectedNumDice, roll);
            probabilities.push([roll, probability]);
            avg += roll * probability;
            roll += 1;
        }
        setSelectedResults(
            probabilities.map(([timesRolled, proportion]) => ({
                name: timesRolled.toString(),
                proportion: proportion,
            }))
        );
    }, [selectedNumDice]);

    return (
        <HeaderFooter title="Diminishing Pools" back="/dice" infoDialog={info}>
            <Grid container>
                <Grid item xs={12} sm={2}>
                    <TableContainer sx={{ maxHeight: "30rem" }}>
                        <Table stickyHeader>
                            <TableHead>
                                <TableRow>
                                    <TableCell>Dice</TableCell>
                                    <TableCell align="right">
                                        Average rolls until depleted
                                    </TableCell>
                                </TableRow>
                            </TableHead>
                            <TableBody>
                                {expectedValues.map(([n, e]) => (
                                    <TableRow
                                        key={n}
                                        hover={true}
                                        selected={n === selectedNumDice}
                                        onClick={() => {
                                            setSelectedNumDice(n);
                                        }}
                                    >
                                        <TableCell>{n}</TableCell>
                                        <TableCell align="right">{e.toFixed(3)}</TableCell>
                                    </TableRow>
                                ))}
                            </TableBody>
                        </Table>
                    </TableContainer>
                </Grid>
                <Grid item xs={12} sm={10} sx={{ minHeight: { xs: "90vh", sm: 100 } }}>
                    <ResponsiveContainer width="100%" height="100%">
                        <BarChart
                            width={4}
                            height={4}
                            data={selectedResults}
                            margin={{
                                top: 5,
                                right: 30,
                                left: 20,
                                bottom: 5,
                            }}
                        >
                            <XAxis dataKey="name" dy={0}>
                                {/* <Label >Number of rolls until pool is depleted</Label> */}
                            </XAxis>
                            <YAxis />
                            <Tooltip
                                cursor={{ fill: colors.gray }}
                                contentStyle={{ backgroundColor: colors.darkGray }}
                                labelFormatter={(value) => {
                                    return `${value} roll${value == 1 ? "" : "s"} until depletion`;
                                }}
                                formatter={proportionFormat}
                            />
                            {/* <Legend /> */}

                            <Bar
                                dataKey="proportion"
                                fill={colors.blue}
                                activeBar={<Rectangle fill={colors.pink} stroke={colors.black} />}
                            />
                            {/* <ReferenceLine x={3.2} strokeWidth={3} stroke="red" /> */}
                        </BarChart>
                    </ResponsiveContainer>
                </Grid>
            </Grid>
        </HeaderFooter>
    );
}
