import { useState } from "react";
import rollsData from "../../static/stats/rolls.json";
import HeaderFooter from "../HeaderFooter";
import {
    FormControl,
    Grid,
    InputLabel,
    OutlinedInput,
    useMediaQuery,
    useTheme,
} from "@mui/material";
import { BarChart, Bar, Rectangle, XAxis, YAxis, Tooltip, ResponsiveContainer } from "recharts";

import _ from "lodash";
import { colors } from "../../theme";
import { proportionFormat } from "./DiminishingPoolsAnalysis";
const data: { [d: string]: { [t: string]: (typeof rollsData)["1"]["0"] } } = rollsData;
const barColors: { [r: string]: string } = {
    disaster: colors.red,
    grim: colors.lightGray,
    messy: colors.yellow,
    perfect: colors.green,
    critical: colors.blue,
};

const numDiceOptions = Object.keys(data).sort();
const numThornsOptions = Object.keys(data["1"]).sort();
const info = (
    <>
        The data on this page was generated by simulating 10^8 rolls of a set of dice for each
        combination of the size of the dice pool and the number of thorns.
    </>
);

export default function RollsWithThornsAnalysis() {
    const theme = useTheme();
    const mobileScreen = useMediaQuery(theme.breakpoints.between("xs", "sm"));
    const [selectedNumDice, setSelectedNumDice] = useState("4");
    const [selectedNumThorns, setSelectedNumThorns] = useState("1");
    const selectedRow = data[selectedNumDice][selectedNumThorns];
    const maxProportion = _.max(
        Object.values(data)
            .map((r) => Object.values(r))
            .flat()
            .flat()
            .map((r) => r.proportion)
    );
    return (
        <HeaderFooter title="Rolls with Thorns" back="/dice" infoDialog={info}>
            <Grid container justifyContent={"center"}>
                <Grid item>
                    <Grid
                        container
                        spacing={2}
                        // marginLeft={{ xs: 5, sm: 0 }}
                    >
                        <Grid item>
                            <FormControl>
                                <InputLabel id="dice">Number of dice</InputLabel>
                                <OutlinedInput
                                    inputProps={{
                                        min: numDiceOptions[0],
                                        max: numDiceOptions[numDiceOptions.length - 1],
                                    }}
                                    type="number"
                                    value={selectedNumDice}
                                    label="Number of dice"
                                    id="dice"
                                    onChange={(e) => {
                                        setSelectedNumDice(e.target.value);
                                    }}
                                    sx={{ minWidth: { sm: "250px", xs: "175px" } }}
                                />
                            </FormControl>
                        </Grid>
                        <Grid item>
                            <FormControl>
                                <InputLabel id="thorns">Number of thorns</InputLabel>
                                <OutlinedInput
                                    inputProps={{
                                        min: numThornsOptions[0],
                                        max: numThornsOptions[numThornsOptions.length - 1],
                                    }}
                                    value={selectedNumThorns.toString()}
                                    type="number"
                                    label="Number of thorns"
                                    id="thorns"
                                    onChange={(e) => {
                                        setSelectedNumThorns(e.target.value);
                                    }}
                                    sx={{ minWidth: { sm: "250px", xs: "175px" } }}
                                />
                            </FormControl>
                        </Grid>
                    </Grid>
                </Grid>
                <Grid item xs={12}>
                    <div style={{ width: "100vw", height: "60vh" }}>
                        <ResponsiveContainer>
                            <BarChart
                                width={8}
                                height={4}
                                data={selectedRow.map((r) => ({ ...r, fill: barColors[r.result] }))}
                                margin={{
                                    top: 30,
                                    right: 30,
                                    left: 5,
                                    bottom: 30,
                                }}
                            >
                                <XAxis
                                    dataKey="result"
                                    angle={mobileScreen ? -45 : 0}
                                    textAnchor={mobileScreen ? "end" : "middle"}
                                />
                                <YAxis
                                    allowDataOverflow={true}
                                    domain={[
                                        0,
                                        maxProportion
                                            ? Number(maxProportion.toPrecision(2))
                                            : "auto",
                                    ]}
                                />
                                <Tooltip
                                    cursor={{ fill: colors.gray }}
                                    contentStyle={{ backgroundColor: colors.darkGray }}
                                    formatter={proportionFormat}
                                />
                                <Bar
                                    dataKey="proportion"
                                    fill={colors.white}
                                    activeBar={<Rectangle stroke={colors.lightGray} />}
                                />
                            </BarChart>
                        </ResponsiveContainer>
                    </div>
                </Grid>
            </Grid>
        </HeaderFooter>
    );
}
